# Generated by Django 3.2.5 on 2021-09-11 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_auto_20210911_1543'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='type',
            new_name='category',
        ),
    ]
